Added Mal And Anilist to Kawaiifu, DubbedAnime, And AllAnime
recloudstream/cloudstream-extensions pull request #38
Opened 2023-02-05 04:58 UTC by KillerDogeEmpire

2023-02-05 12:08 UTC, anotherduckling commented
possibly

2023-02-06 02:11 UTC, KillerDogeEmpire commented
It works

2023-02-06 17:48 UTC, Blatzar requested changes
Honestly surprisingly well functioning tracker, however there are some things which needs changing, and I would really want the getTracker inside the main app so all providers can use it.

Also make sure you update the version code on providers you update :pray:

2023-02-06 17:48 UTC, Blatzar commented on AllAnimeProvider/src/main/kotlin/com/lagradost/AllAnimeProvider.kt
> +        val typeCheck =
This is unused

2023-02-06 17:48 UTC, Blatzar commented on AllAnimeProvider/src/main/kotlin/com/lagradost/AllAnimeProvider.kt
> +        val document = app.get(url).document
Please dont do unnecessary requests, the document is already fetched below

2023-02-06 17:48 UTC, Blatzar commented on AllAnimeProvider/src/main/kotlin/com/lagradost/AllAnimeProvider.kt
> +        val (malId, anilistId, image, cover) = getTracker(title, "tv", year)
the year variable in this case is R.string.year which equals 2131886889, use showData.airedStart?.year

2023-02-06 17:48 UTC, Blatzar commented on AllAnimeProvider/src/main/kotlin/com/lagradost/AllAnimeProvider.kt
> +        val (malId, anilistId, image, cover) = getTracker(title, "tv", year)
image and cover is unused :pensive: 
You can do val (malId, anilistId, _, _) then

2023-02-06 17:48 UTC, Blatzar commented on AnimePaheProvider/src/main/kotlin/com/lagradost/AnimePaheProvider.kt
> +        const val MAIN_URL = "https://animepahe.ru"
Remember to update version int

2023-02-06 17:48 UTC, Blatzar commented on AllAnimeProvider/src/main/kotlin/com/lagradost/AllAnimeProvider.kt
> +    private suspend fun getTracker(title: String?, type: String?, year: Int?): Tracker {
This is a great method, perhaps so great it should be moved to the core app, to prevent code duplication.
What do you think @KillerDogeEmpire ?

2023-02-06 18:54 UTC, KillerDogeEmpire commented on AllAnimeProvider/src/main/kotlin/com/lagradost/AllAnimeProvider.kt
> +    private suspend fun getTracker(title: String?, type: String?, year: Int?): Tracker {
@Blatzar sure, the method was discovered by hexated, he let me use it to add the tracker to the anime providers, you can add it to the main core of the app. I will make these changes later. Thanks for reviewing the PR

2023-02-06 18:57 UTC, KillerDogeEmpire commented on AllAnimeProvider/src/main/kotlin/com/lagradost/AllAnimeProvider.kt
> +    private suspend fun getTracker(title: String?, type: String?, year: Int?): Tracker {
And yea, I totally agree, this should be in the core app so other providers can use it.

2023-02-09 00:08 UTC, closed without merging